### ISSUE TITLE
Cannot sign up

### ISSUE THREAD

**Issue by lmiller1990** [johnhckuo/Block-Farm#53]
Hey,

I tried signing up using the herokuapp but got "oops". I tried again and it said "email exists". I guess i t created (with error?).

I then tried to login but it says "please check your inbox" but I got no email.

Any way to sign up?

**Comment by johnhckuo** [comment]
Hi @lmiller1990 
Thanks for the feedback! I've fixed the issue and it should works now.
But you will have to register again.

**Comment by lmiller1990** [comment]
Thanks for the quick turnaround. I'll give it a shot tomorrow. Great job on the app!

Do you have blog/medium/something I can follow you?

**Comment by johnhckuo** [comment]
@lmiller1990 Thanks for the issue you've reported :)
I've written some posts on my own site (http://johnhckuo.github.io/blog/) irregularly.
But recently I'm working on some WebGL projects and doesn't have much spare time on the blog. :p  
Maybe I'll update some posts in the following weeks.
